### ISSUE TITLE
Flask API 增加測試與Swagger 文件

### ISSUE THREAD

**Issue by passontw** [passoncomtw/splitbill-services#8]
# 功能內容

* Swagger UI
* Unitest  

# 參考資料

[flask-crud-swagger-api](https://github.com/ashishsalunkhe/flask-crud-swagger-api)

[Flask api unitest](https://www.maxlist.xyz/2020/08/17/flask-unittest/)

[flask crud tutorial](https://medium.com/@hillarywando/how-to-create-a-basic-crud-api-using-python-flask-cd68ef5fd7e3)

**Comment by RobYang203** [comment]
@passontw 測試指令有改，再麻煩調整，謝謝
